export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  liveWarningFeedUrl: process.env.LIVE_WARNING_FEED_URL ?? "",
  liveWarningFeedName: process.env.LIVE_WARNING_FEED_NAME ?? "Configured official feed",
  liveWarningFeedType: process.env.LIVE_WARNING_FEED_TYPE ?? "CAP/RSS",
  geocoderUrl: process.env.GEOCODER_URL ?? "https://nominatim.openstreetmap.org/search",
  routerUrl: process.env.ROUTER_URL ?? "https://router.project-osrm.org/route/v1/driving",
  shelterAvailabilityUrl: process.env.SHELTER_AVAILABILITY_URL ?? "",
  openRouterApiKey: process.env.OPENROUTER_API_KEY ?? "",
  openRouterModel: process.env.OPENROUTER_MODEL ?? "openai/gpt-4o-mini",
};
